version: '3'
services:
  devcamp-auth-service:
    image: harbor.entelectprojects.co.za/internaltraining-devcamp/devcamp-auth-service:latest
    container_name: DevCamp-Auth-Service
    ports:
      - 8080:8080

  devcamp-kyc-service:
    image: harbor.entelectprojects.co.za/internaltraining-devcamp/devcamp-kyc-service:latest
    container_name: DevCamp-KYC-Service
    environment:
      - Application__PublicKey=${PUB_KEY}
      - Application__FailureResponses__Error4xx__FrequencyPercentage=10
      - Application__FailureResponses__Error5xx__FrequencyPercentage=20
    ports:
      - 8081:80

  devcamp-dha-service:
    image: harbor.entelectprojects.co.za/internaltraining-devcamp/devcamp-dha-service:latest
    container_name: DevCamp-DHA-Service
    environment:
      - Application__PublicKey=${PUB_KEY}
      - Application__FailureResponses__Error4xx__FrequencyPercentage=10
      - Application__FailureResponses__Error5xx__FrequencyPercentage=20
    ports:
      - 8082:80

  devcamp-creditcheck-service:
    image: harbor.entelectprojects.co.za/internaltraining-devcamp/devcamp-creditcheck-service
    container_name: DevCamp-CreditCheck-Service
    environment:
      - Application__FailureResponses__Error4xx__FrequencyPercentage=10
    ports:
      - 8083:80

  devcamp-cis-service:
    image: harbor.entelectprojects.co.za/internaltraining-devcamp/devcamp-cis-service:latest
    container_name: DevCamp-CIS-Service
    ports:
      - 8084:8080

  devcamp-db:
      image: postgres:14.2
      container_name: DevCamp-Postgres-db
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=user
      volumes:
        - db-data:/var/lib/postgresql/data

volumes:
  db-data: