---
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /token:
    post:
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string

      security:
        - basicAuth: []
      tags:
        - authentication-controller
      operationId: token
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
        "401":
          description: Not Authenticated
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
